# Site settings
title: Panorama 360
email: rafsilva@isi.edu
description: > # this means to ignore newlines until "baseurl:"
  Panorama 360

# Build settings
markdown: kramdown

assets:
  sources:
    - assets/fonts
    - assets/images
    - assets/js
    - assets/css

gems:
  - jekyll-assets

